### ISSUE TITLE
How do you add lodash to this build?

### ISSUE THREAD

**Issue by markoddi** [2sic/app-tutorial-angular4-hello-dnn#1]
How do you add lodash to this build or any third party library's?

I then want to run ng build --prod --aot --output-hashing=none but see it in the browser.

Question 1: how do I add lodash?

Question 2: how do I view the ng build --prod --aot --output-hashing=none but see it in the browser.

Kind regards

**Comment by iJungleboy** [comment]
Just for clarity: are you using this inside DNN, or outside of DNN? It's meant to be used in DNN.

**Comment by markoddi** [comment]
I managed to get this working now.
I used http-server ./dist

Yeh im using the DNN seed app
